version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: finances
      DATABASE_USER: usr_finance_bot
      DATABASE_PASSWORD: postgres
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: usr_finance_bot
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
