# Generated by Django 5.1.6 on 2025-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_user_id_category_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
