# Generated by Django 5.1.7 on 2025-06-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_category_normalized_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
