orchestration_task:
  description: Manage the interaction between different agents.
  expected_output: >
    Based on the user's prompt, determine which agent should handle the request. The output should be a JSON formatted structure.

    The user prompt that needs to be processed is: {prompt}

    The output must have the following keys:
      - **agent_name**: The name of the agent to perform the task. `finances_manager` if the tasks is related to finance management, `price_researcher` if the task is related to price research.
      - **prompt**: The prompt that will be sent to the agent.
      - **description**: A description of the task that will be performed by the agent.
      - **product**: The name of the product if the task is related to price research.
    
    ## Examples of prompts for `finances_manager`
      - "Groceries 500"
      - "Rent 1200"
      - "Can you help me update my rent payment?"
      - "I want to delete my last transaction."
      - "Please read my last transaction."

    ## Examples of prompts for `price_researcher`
      - "Can you find the best price for a new laptop?"
      - "I need to know the price of the latest iPhone."
      - "What is the best price for a Samsung Galaxy?"
      - "Find me the cheapest price for a pair of shoes."
      - "Research the price of a new TV."
  agent: orchestrator