# Generated by Django 5.1.7 on 2025-09-04 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinteraction'),
        ),
    ]
