# Generated by Django 5.1.7 on 2025-09-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userinteraction_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
