# Generated by Django 5.1.7 on 2025-09-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('message', 'Message'), ('response', 'Response')], max_length=8),
        ),
    ]
