# Generated by Django 5.1.7 on 2025-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_bot', '0002_agentsettings_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='model',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
    ]
