# Generated by Django 5.1.7 on 2025-06-28 17:19

from django.db import migrations


def seed_default_agent_settings(apps, schema_editor):
    model = apps.get_model('langchain_bot', 'AgentSettings')
    if not model.objects.filter(is_default=True).exists():
        with open('conf/prompt.txt', 'r', encoding='utf-8') as prompt_buf:
            prompt = prompt_buf.read()
            model.objects.create(
                prompt=prompt,
                is_default=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_bot', '0003_agentsettings_model'),
    ]

    operations = [
        migrations.RunPython(seed_default_agent_settings),
    ]
