# Generated by Django 5.1.7 on 2025-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_bot', '0004_agent_settings_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsettings',
            name='model',
            field=models.CharField(default='gpt-5-mini', max_length=100),
        ),
    ]
