# Generated by Django 5.1.7 on 2025-05-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('rate_limit_enabled', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=100)),
            ],
        ),
    ]
