# Generated by Django 5.1.7 on 2025-06-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramusersettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramusersettings',
            options={'verbose_name': 'User settings (Telegram)', 'verbose_name_plural': 'User settings (Telegram)'},
        ),
    ]
